"""
Document Payload Format Documentation

This file defines the complete payload format for storing document data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).

Documents can be associated with multiple source tables (suppliers, products, requests) via mapping_id and source_table.
"""

from typing import Any, Dict, List, Optional
from datetime import datetime

# ============================================================================
# DOCUMENT PAYLOAD FORMAT
# Single payload structure with all document fields
# Documents can be linked to suppliers, products, or requests via mapping_id and source_table
# ============================================================================

DOCUMENT_PAYLOAD: Dict[str, Any] = {
    # ========================================================================
    # PRIMARY KEY & IDENTIFIERS
    # ========================================================================
    
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented document ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # ========================================================================
    # DOCUMENT FILE INFORMATION
    # ========================================================================
    
    # Column: path | Type: String(255) | Nullable
    # Description: Document file path - Storage path of the document file
    "path": "/documents/suppliers/123/certificate.pdf",
    
    # Column: url | Type: String(255) | Nullable
    # Description: Document URL - Public URL to access the document
    "url": "https://example.com/documents/certificate.pdf",
    
    # Column: file_name | Type: String(255) | Nullable
    # Description: File name - Original file name of the document
    "file_name": "ISO_Certificate_2025.pdf",
    
    # Column: file_type | Type: String(255) | Nullable
    # Description: File type - MIME type or file extension (e.g., 'application/pdf', 'image/jpeg')
    "file_type": "application/pdf",
    
    # Column: file_size | Type: Integer | Nullable
    # Description: File size - Size of the document file in bytes
    "file_size": 245760,
    
    # ========================================================================
    # SOURCE & MAPPING INFORMATION
    # ========================================================================
    
    # Column: source | Type: String(255) | Nullable
    # Description: Document source - Source system where document originated
    # Enum values: 'email', 'bitrix', 'onedrive'
    "source": "bitrix",
    
    # Column: mapping_id | Type: Integer | Nullable
    # Description: Mapping ID - Foreign key to the source table (suppliers.id, products.id, or requests.id)
    # This links the document to the parent entity (supplier, product, or request)
    "mapping_id": 123,
    
    # Column: source_table | Type: String(255) | Nullable
    # Description: Source table - Name of the table this document is associated with
    # Enum values: 'suppliers', 'products', 'requests'
    # This determines which table mapping_id refers to
    "source_table": "suppliers",
    
    # ========================================================================
    # METADATA & AUDIT FIELDS
    # ========================================================================
    
    # Column: created_at | Type: DateTime | Not Null
    # Description: Timestamp when the record was created in the database (auto-generated)
    "created_at": datetime.utcnow().isoformat(),
    
    # Column: updated_at | Type: DateTime | Not Null
    # Description: Timestamp when the record was last updated in the database (auto-generated)
    "updated_at": datetime.utcnow().isoformat(),
    
    # Column: deleted_at | Type: DateTime | Nullable
    # Description: Timestamp when the record was soft deleted (NULL if not deleted)
    "deleted_at": None,
}

# ============================================================================
# DOCUMENT PAYLOAD EXAMPLES FOR DIFFERENT SOURCE TABLES
# ============================================================================

# Example: Document associated with a Supplier
DOCUMENT_SUPPLIER_PAYLOAD: Dict[str, Any] = {
    "path": "/documents/suppliers/123/iso_certificate.pdf",
    "url": "https://storage.example.com/documents/suppliers/123/iso_certificate.pdf",
    "file_name": "ISO_9001_Certificate_2025.pdf",
    "file_type": "application/pdf",
    "file_size": 512000,
    "source": "bitrix",
    "mapping_id": 123,  # suppliers.id
    "source_table": "suppliers",
}

# Example: Document associated with a Product
DOCUMENT_PRODUCT_PAYLOAD: Dict[str, Any] = {
    "path": "/documents/products/10772/technical_spec.pdf",
    "url": "https://storage.example.com/documents/products/10772/technical_spec.pdf",
    "file_name": "Technical_Specification_Butter_100g.pdf",
    "file_type": "application/pdf",
    "file_size": 1024000,
    "source": "bitrix",
    "mapping_id": 10772,  # products.id
    "source_table": "products",
}

# Example: Document associated with a Request/Deal
DOCUMENT_REQUEST_PAYLOAD: Dict[str, Any] = {
    "path": "/documents/requests/5001/contract.pdf",
    "url": "https://storage.example.com/documents/requests/5001/contract.pdf",
    "file_name": "Sales_Contract_Q1_2025.pdf",
    "file_type": "application/pdf",
    "file_size": 2048000,
    "source": "bitrix",
    "mapping_id": 5001,  # requests.id
    "source_table": "requests",
}

# Example: Document from Email/OneDrive
DOCUMENT_EMAIL_PAYLOAD: Dict[str, Any] = {
    "path": "/documents/emails/attachment_12345.pdf",
    "url": "https://storage.example.com/documents/emails/attachment_12345.pdf",
    "file_name": "Invoice_2025_01.pdf",
    "file_type": "application/pdf",
    "file_size": 256000,
    "source": "email",
    "mapping_id": 100,  # Could be supplier, product, or request ID
    "source_table": "suppliers",  # or "products" or "requests"
}

