"""
Supplier Payload Format Documentation

This file defines the complete payload format for storing supplier data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).
"""

from typing import Any, Dict, List, Optional


# ============================================================================
# SUPPLIER PAYLOAD FORMAT
# Single payload structure with all supplier fields and bridge table mappings
# ============================================================================

SUPPLIER_PAYLOAD: Dict[str, Any] = {
    # ========================================================================
    # PRIMARY KEY & IDENTIFIERS
    # ========================================================================
    
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented supplier ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: bitrix_id | Type: Integer | Required | Not Null
    # Description: Bitrix24 supplier ID - Unique identifier from Bitrix24 system
    "bitrix_id": 12345,
    
    # Column: uuid | Type: String(255) | Nullable
    # Description: UUID - Universal unique identifier for supplier
    "uuid": "550e8400-e29b-41d4-a716-446655440000",
    
    # ========================================================================
    # BASIC COMPANY INFORMATION
    # ========================================================================
    
    # Column: company_name | Type: String(255) | Nullable
    # Description: Supplier company name - Official company name
    "company_name": "Dana Dairy Products Ltd.",
    
    # Column: supplier_name | Type: String(255) | Nullable
    # Description: Supplier Name - Alternative supplier name
    "supplier_name": "Dana Dairy",
    
    # Column: company_type | Type: String(255) | Nullable
    # Description: Type of company - Company type (supplier, manufacturer, distributor, retailer, other)
    "company_type": "supplier",
    
    # Column: industry | Type: String(255) | Nullable
    # Description: Industry Code - Industry classification code
    "industry": "DAIRY",
    
    # Column: logo | Type: JSON | Nullable
    # Description: Company logo file URLs with domain prefix (stored as JSON array/dict)
    "logo": [
        {
            "showUrl": "https://example.com/logos/logo-show.jpg",
            "downloadUrl": "https://example.com/logos/logo-download.jpg"
        }
    ],
    
    # ========================================================================
    # CONTACT INFORMATION (JSON fields - stored as list/dict)
    # ========================================================================
    
    # Column: email | Type: JSON | Nullable
    # Description: E-mail array with VALUE_TYPE, VALUE, TYPE_ID (stored as JSON array)
    "email": [
        {
            "VALUE_TYPE": "WORK",
            "VALUE": "contact@danadairy.com",
            "TYPE_ID": "EMAIL"
        },
        {
            "VALUE_TYPE": "HOME",
            "VALUE": "info@danadairy.com",
            "TYPE_ID": "EMAIL"
        }
    ],
    
    # Column: phone | Type: JSON | Nullable
    # Description: Phone array with ID, VALUE_TYPE, VALUE, TYPE_ID (stored as JSON array)
    "phone": [
        {
            "ID": "123",
            "VALUE_TYPE": "WORK",
            "VALUE": "+55 11 98765-4321",
            "TYPE_ID": "PHONE"
        }
    ],
    
    # Column: website | Type: JSON | Nullable
    # Description: Website array with VALUE_TYPE, VALUE, TYPE_ID (stored as JSON array)
    "website": [
        {
            "VALUE_TYPE": "WORK",
            "VALUE": "https://www.danadairy.com",
            "TYPE_ID": "WEB"
        }
    ],
    
    # Column: messenger | Type: String(255) | Nullable
    # Description: Messenger - Messenger contact information
    "messenger": "WhatsApp: +55 11 98765-4321",
    
    # ========================================================================
    # STATUS & FLAGS (Boolean fields)
    # ========================================================================
    
    # Column: has_phone | Type: Boolean | Nullable | Default: False
    # Description: Whether has phone number - Phone availability flag
    # Enum: True = Supplier has phone number, False = Supplier has no phone number
    "has_phone": True,
    
    # Column: has_email | Type: Boolean | Nullable | Default: False
    # Description: Whether has email address - Email availability flag
    # Enum: True = Supplier has email address, False = Supplier has no email address
    "has_email": True,
    
    # Column: has_open_channel | Type: Boolean | Nullable | Default: False
    # Description: Whether has open channel - Open channel availability flag
    # Enum: True = Supplier has open channel, False = Supplier has no open channel
    "has_open_channel": False,
    
    # Column: has_products | Type: Boolean | Nullable | Default: False
    # Description: Whether supplier has products - Product association flag
    # Enum: True = Supplier has associated products, False = Supplier has no products
    "has_products": True,
    
    # Column: available_to_everyone | Type: Boolean | Nullable | Default: False
    # Description: Whether available to everyone - Visibility flag
    # Enum: True = Supplier is available to everyone, False = Supplier is restricted
    "available_to_everyone": False,
    
    # Column: my_company | Type: Boolean | Nullable | Default: False
    # Description: Whether my company - Internal company flag
    # Enum: True = Supplier is our company, False = Supplier is external
    "my_company": False,
    
    # Column: origin_accepted | Type: Boolean | Nullable | Default: False
    # Description: Whether origin is accepted - Origin acceptance flag
    # Enum: True = Origin is accepted, False = Origin is not accepted
    "origin_accepted": True,
    
    # Column: purchased | Type: Boolean | Nullable | Default: False
    # Description: Whether purchased - Purchase status flag
    # Enum: True = Supplier has been purchased from, False = Supplier has not been purchased from
    "purchased": False,
    
    # ========================================================================
    # PRODUCT ASSOCIATIONS
    # ========================================================================
    
    # Column: linked_products_count | Type: Integer | Nullable | Default: 0
    # Description: Number of linked products - Count of associated products
    "linked_products_count": 5,
    
    # Column: linked_products | Type: String(255) | Nullable
    # Description: List of linked product names - Comma-separated product names (stored as string)
    "linked_products": "Butter, Cheese, Milk, Yogurt, Cream",
    
    # ========================================================================
    # LEAD & RESPONSIBILITY
    # ========================================================================
    
    # Column: lead | Type: Integer | Nullable
    # Description: Lead identifier - Lead ID from Bitrix24
    "lead": 1001,
    
    # Column: responsible_person | Type: String(255) | Nullable
    # Description: Responsible person Id - Bitrix user ID of responsible person
    "responsible_person": "218",
    
    # Column: created_by | Type: String(255) | Nullable
    # Description: User who created - Bitrix user ID who created the supplier
    "created_by": "78",
    
    # Column: modified_by | Type: String(255) | Nullable
    # Description: User who last modified - Bitrix user ID who last modified the supplier
    "modified_by": "218",
    
    # ========================================================================
    # FINANCIAL INFORMATION
    # ========================================================================
    
    # Column: payment_details | Type: String(255) | Nullable
    # Description: Payment details - Payment terms and details
    "payment_details": "Net 30 days, Bank transfer",
    
    # Column: annual_revenue | Type: Integer | Nullable
    # Description: Annual revenue - Annual revenue amount
    "annual_revenue": 5000000,
    
    # Column: currency | Type: String(255) | Nullable
    # Description: Currency code - ISO currency code (e.g., 'USD', 'EUR', 'BRL')
    "currency": "BRL",
    
    # Column: employees | Type: String(255) | Nullable
    # Description: Number of employees - Employee count category (e.g., EMPLOYEES_2)
    "employees": "EMPLOYEES_2",
    
    # ========================================================================
    # ADDRESS INFORMATION (Primary Address)
    # ========================================================================
    
    # Column: street_address | Type: String(255) | Nullable
    # Description: Street address - Primary street address
    "street_address": "123 Main Street",
    
    # Column: address_line_2 | Type: String(255) | Nullable
    # Description: Address line 2 - Secondary address line
    "address_line_2": "Suite 100",
    
    # Column: city | Type: String(255) | Nullable
    # Description: City - City name
    "city": "São Paulo",
    
    # Column: zip | Type: String(255) | Nullable
    # Description: Zip code - Postal/ZIP code
    "zip": "01310-100",
    
    # Column: region | Type: String(255) | Nullable
    # Description: Region - Region/State name
    "region": "Southeast",
    
    # Column: state | Type: String(255) | Nullable
    # Description: State / Province - State or province name
    "state": "São Paulo",
    
    # Column: country | Type: Text | Nullable
    # Description: Country (may include coordinates) - Country name (stored as string)
    "country": "Brazil",
    
    # Column: country_code | Type: String(255) | Nullable
    # Description: Country code - ISO country code (e.g., 'BR', 'US', 'UK')
    "country_code": "BR",
    
    # Column: location_address_id | Type: Integer | Nullable
    # Description: Location address identifier - Address location ID
    "location_address_id": 123,
    
    # ========================================================================
    # BILLING ADDRESS INFORMATION
    # ========================================================================
    
    # Column: billing_address | Type: String(255) | Nullable
    # Description: Billing address - Billing street address
    "billing_address": "456 Billing Street",
    
    # Column: billing_address_line_2 | Type: String(255) | Nullable
    # Description: Billing address line 2 - Billing secondary address line
    "billing_address_line_2": "Floor 2",
    
    # Column: billing_city | Type: String(255) | Nullable
    # Description: Billing city - Billing city name
    "billing_city": "São Paulo",
    
    # Column: billing_zip | Type: String(255) | Nullable
    # Description: Billing zip code - Billing postal/ZIP code
    "billing_zip": "01310-200",
    
    # Column: billing_region | Type: String(255) | Nullable
    # Description: Billing region - Billing region name
    "billing_region": "Southeast",
    
    # Column: billing_state | Type: String(255) | Nullable
    # Description: Billing State / Province - Billing state or province name
    "billing_state": "São Paulo",
    
    # Column: billing_country | Type: String(255) | Nullable
    # Description: Billing country - Billing country name
    "billing_country": "Brazil",
    
    # Column: billing_country_code | Type: String(255) | Nullable
    # Description: Billing country code - Billing ISO country code
    "billing_country_code": "BR",
    
    # ========================================================================
    # LEGAL ADDRESS INFORMATION
    # ========================================================================
    
    # Column: legal_address | Type: String(255) | Nullable
    # Description: Legal address - Legal registered address
    "legal_address": "789 Legal Street",
    
    # Column: legal_address_location_address_id | Type: Integer | Nullable
    # Description: Legal address location address identifier - Legal address location ID
    "legal_address_location_address_id": 456,
    
    # ========================================================================
    # COMMENTS & NOTES (Text fields - stored as string)
    # ========================================================================
    
    # Column: comment | Type: Text | Nullable
    # Description: Supplier comment - General comments about supplier (stored as string)
    "comment": "Premium dairy supplier with excellent quality products. Established in 1990.",
    
    # Column: products_manufactured | Type: Text | Nullable
    # Description: Products manufactured - List of products manufactured (stored as string)
    "products_manufactured": "Butter, Cheese, Milk, Yogurt, Cream, Ice Cream",
    
    # ========================================================================
    # METADATA & AUDIT FIELDS (DateTime stored as string in ISO format)
    # ========================================================================
    
    # Column: created_on | Type: DateTime | Nullable
    # Description: Creation date - Supplier creation date from Bitrix24 (stored as string)
    "created_on": "2025-01-15T10:30:00+03:00",
    
    # Column: modified_on | Type: DateTime | Nullable
    # Description: Last modification timestamp - Last update time from Bitrix24 (stored as string)
    "modified_on": "2025-12-29T14:20:00+03:00",
    
    # Column: last_updated_on | Type: DateTime | Nullable
    # Description: Last update timestamp - Last update timestamp (stored as string)
    "last_updated_on": "2025-12-29T14:20:00+03:00",
    
    # Column: last_contact | Type: String(255) | Nullable
    # Description: Last contact - Last contact date or information
    "last_contact": "2025-12-20",
    
    # Column: date_of_inquiry | Type: DateTime | Nullable
    # Description: Date of Inquiry (inquiry date / cold contact date) - Inquiry date (stored as string)
    "date_of_inquiry": "2025-01-10T09:00:00+03:00",
    
    # ========================================================================
    # EXTERNAL SOURCE & VERSIONING
    # ========================================================================
    
    # Column: external_source | Type: String(255) | Nullable
    # Description: External source - Source system identifier
    "external_source": "bitrix",
    
    # Column: item_id_in_data_source | Type: String(255) | Nullable
    # Description: Item ID in data source - External system item ID
    "item_id_in_data_source": "EXT123456",
    
    # Column: original_version | Type: Integer | Nullable
    # Description: Original version - Version number from source system
    "original_version": 1,
    
    # ========================================================================
    # MARKETING & CAMPAIGN INFORMATION
    # ========================================================================
    
    # Column: ad_system | Type: String(255) | Nullable
    # Description: Ad system - Advertising system identifier
    "ad_system": "google",
    
    # Column: medium | Type: String(255) | Nullable
    # Description: Medium - Marketing medium
    "medium": "cpc",
    
    # Column: ad_campaign_utm | Type: String(255) | Nullable
    # Description: Ad campaign UTM - UTM campaign identifier
    "ad_campaign_utm": "summer_sale_2025",
    
    # Column: campaign_contents | Type: String(255) | Nullable
    # Description: Campaign contents - Campaign content identifier
    "campaign_contents": "banner_ad_v1",
    
    # Column: campaign_search_term | Type: String(255) | Nullable
    # Description: Campaign search term - Search term used in campaign
    "campaign_search_term": "dairy products",
    
    # Column: last_timeline_activity_added_by | Type: String(255) | Nullable
    # Description: User who last added timeline activity - Bitrix user ID
    "last_timeline_activity_added_by": "218",
    
    # ========================================================================
    # BUSINESS CLASSIFICATION
    # ========================================================================
    
    # Column: type_of_buyer | Type: String(255) | Nullable
    # Description: Type of Buyer - Buyer type classification
    "type_of_buyer": "wholesale",
    
    # Column: prefix | Type: String(255) | Nullable
    # Description: Prefix - Name prefix or title
    "prefix": "Mr.",
    
    # Column: product_category | Type: Text | Nullable
    # Description: Product Category (can be boolean or string) - Product category (stored as string)
    "product_category": "dairy",
    
    # Column: sub_category | Type: String(255) | Nullable
    # Description: Sub category - Product sub-category
    "sub_category": "uht-milk",
    
    # Column: child_category | Type: String(255) | Nullable
    # Description: Child category - Product child category
    "child_category": "uht-milk-1",
    
    # ========================================================================
    # CERTIFICATES & COMPLIANCE (JSON and Text fields)
    # ========================================================================
    
    # Column: certificates | Type: JSON | Nullable
    # Description: Certificates array with showUrl and downloadUrl (stored as JSON array)
    "certificates": [
        {
            "showUrl": "https://example.com/certs/cert1-show.jpg",
            "downloadUrl": "https://example.com/certs/cert1-download.pdf"
        },
        {
            "showUrl": "https://example.com/certs/cert2-show.jpg",
            "downloadUrl": "https://example.com/certs/cert2-download.pdf"
        }
    ],
    
    # Column: factory_certificates | Type: Text | Nullable
    # Description: Factory certificates: a. ISO b. HACCP b. FSSC c. GMP d. LICENSE (stored as string)
    "factory_certificates": "ISO: Yes, HACCP: Yes, FSSC: Yes, GMP: Yes, LICENSE: Yes",
    
    # Column: ops | Type: String(255) | Nullable
    # Description: OPS - Operations identifier
    "ops": "OPS001",
    
    # Column: health_mark | Type: String(255) | Nullable
    # Description: Health Mark - Health certification mark
    "health_mark": "HM12345",
    
    # ========================================================================
    # TAGS & CLASSIFICATION (Text fields - can be boolean or string)
    # ========================================================================
    
    # Column: hashtag | Type: Text | Nullable
    # Description: #TAG (can be boolean or string) - Hashtag or tag (stored as string)
    "hashtag": "#premium #dairy #certified",
    
    # Column: new_list | Type: String(255) | Nullable
    # Description: New list - List identifier
    "new_list": "LIST001",
    
    # Column: new_text | Type: Text | Nullable
    # Description: New text (can be boolean or string) - New text field (stored as string)
    "new_text": "New supplier added in 2025",
    
    # ========================================================================
    # ORDER & VOLUME INFORMATION
    # ========================================================================
    
    # Column: week_commitment | Type: Integer | Nullable
    # Description: Week commitment - Weekly commitment volume
    "week_commitment": 100,
    
    # Column: annual_order_volume | Type: String(255) | Nullable
    # Description: Annual Order Volume (FCLs) - Annual order volume in FCLs
    "annual_order_volume": "500",
    
    # Column: estimated_volume | Type: Integer | Nullable
    # Description: Estimated volume - Estimated order volume
    "estimated_volume": 10000,
    
    # ========================================================================
    # RATING & RANKING
    # ========================================================================
    
    # Column: stars | Type: String(255) | Nullable
    # Description: Stars - Rating stars (1-5)
    "stars": "5",
    
    # Column: projected | Type: String(255) | Nullable
    # Description: Projected - Projected value or status
    "projected": "high",
    
    # Column: lead_rank | Type: String(255) | Nullable
    # Description: Lead Rank - Lead ranking value
    "lead_rank": "A",
    
    # ========================================================================
    # LOST & REASON
    # ========================================================================
    
    # Column: lost_reason | Type: String(255) | Nullable
    # Description: Lost reason - Reason for lost deal or opportunity
    "lost_reason": "",
    
    # ========================================================================
    # TAX & REGISTRATION
    # ========================================================================
    
    # Column: rq_vat_id | Type: String(255) | Nullable
    # Description: RQ VAT ID - VAT registration number
    "rq_vat_id": "BR12345678901234",
    
    # Column: registration_number | Type: String(255) | Nullable
    # Description: Registration Number - Company registration number
    "registration_number": "REG123456789",
    
    # ========================================================================
    # BRIDGE TABLE MAPPINGS
    # ========================================================================
    
    # Bridge Table: product_suppliers
    # Table: product_suppliers | Relationship: Many-to-Many (Suppliers ↔ Products)
    # Description: Store multiple product associations for a supplier
    # Fields: supplier_id (FK -> suppliers.id), product_id (FK -> products.id), name, id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "product_suppliers": [
        {
            # Column: product_id | Type: Integer | Required | FK: products.id
            # Description: Product ID - Foreign key to products table
            "product_id": 1,
            
            # Column: name | Type: String(255) | Nullable
            # Description: Name - Mapping name or description
            "name": "Primary Product",
        },
        {
            "product_id": 2,
            "name": "Secondary Product",
        },
    ],
    
    # Bridge Table: supplier_emails
    # Table: supplier_emails | Relationship: One-to-Many (Supplier → SupplierEmails)
    # Description: Store additional email addresses for a supplier
    # Fields: supplier_id (FK -> suppliers.id), email, conversation_id, id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "supplier_emails": [
        {
            # Column: email | Type: String(255) | Nullable
            # Description: Email address - Additional email address
            "email": "sales@danadairy.com",
            
            # Column: conversation_id | Type: String(255) | Nullable
            # Description: Conversation ID - Email conversation identifier
            "conversation_id": "CONV123456",
        },
        {
            "email": "support@danadairy.com",
            "conversation_id": "CONV123457",
        },
    ],
    
    # Bridge Table: documents
    # Table: documents | Relationship: One-to-Many (Supplier → Documents)
    # Description: Store documents associated with a supplier (via mapping_id and source_table)
    # Fields: mapping_id (FK -> suppliers.id when source_table='suppliers'), path, url, file_name, file_type, file_size, source, source_table, id, created_at, updated_at
    # Format: List of dictionaries (stored as list)
    "documents": [
        {
            # Column: path | Type: String(255) | Nullable
            # Description: Path - Document file path
            "path": "/documents/suppliers/123/certificate.pdf",
            
            # Column: url | Type: String(255) | Nullable
            # Description: URL - Document URL
            "url": "https://example.com/documents/certificate.pdf",
            
            # Column: file_name | Type: String(255) | Nullable
            # Description: File name - Document file name
            "file_name": "ISO_Certificate_2025.pdf",
            
            # Column: file_type | Type: String(255) | Nullable
            # Description: File type - Document file type
            "file_type": "application/pdf",
            
            # Column: file_size | Type: Integer | Nullable
            # Description: File size - Document file size in bytes
            "file_size": 245760,
            
            # Column: source | Type: String(255) | Nullable
            # Description: Source - Document source system
            "source": "bitrix",
            
            # Note: mapping_id and source_table are set automatically when creating documents
            # mapping_id: supplier.id
            # source_table: "suppliers"
        },
    ],
    
    # Bridge Table: requests
    # Table: requests | Relationship: One-to-Many (Supplier → Requests)
    # Description: Store request associations for a supplier (via company_id FK in requests table)
    # Fields: company_id (FK -> suppliers.id in requests table), request_id (requests.id)
    # Format: List of dictionaries with only IDs (stored as list)
    "requests": [
        {
            # Column: request_id | Type: Integer | Required | FK: requests.id
            # Description: Request ID - Foreign key to requests table
            "request_id": 100,
        },
        {
            "request_id": 101,
        },
    ],
}

