"""
Customer Payload Format Documentation

This file defines the complete payload format for storing customer data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).
"""

from typing import Any, Dict, List, Optional
from datetime import datetime

# ============================================================================
# CUSTOMER PAYLOAD FORMAT
# Single payload structure with all customer fields and bridge table mappings
# ============================================================================

CUSTOMER_PAYLOAD: Dict[str, Any] = {
    # ========================================================================
    # PRIMARY KEY & IDENTIFIERS
    # ========================================================================
    
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented customer ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # ========================================================================
    # BASIC CUSTOMER INFORMATION
    # ========================================================================
    
    # Column: name | Type: String(255) | Nullable
    # Description: Customer name - Full name of the customer
    "name": "John Smith",
    
    # Column: country | Type: String(255) | Nullable
    # Description: Country - Country where the customer is located (ISO country code or full name)
    "country": "USA",
    
    # Column: email_ids | Type: JSON | Nullable
    # Description: Email IDs as JSON array - Multiple email addresses associated with the customer
    # Format: ["email1@example.com", "email2@example.com"]
    "email_ids": [
        "john.smith@example.com",
        "john@company.com"
    ],
    
    # ========================================================================
    # METADATA & AUDIT FIELDS
    # ========================================================================
    
    # Column: created_at | Type: DateTime | Not Null
    # Description: Timestamp when the record was created in the database (auto-generated)
    "created_at": datetime.utcnow().isoformat(),
    
    # Column: updated_at | Type: DateTime | Not Null
    # Description: Timestamp when the record was last updated in the database (auto-generated)
    "updated_at": datetime.utcnow().isoformat(),
    
    # Column: deleted_at | Type: DateTime | Nullable
    # Description: Timestamp when the record was soft deleted (NULL if not deleted)
    "deleted_at": None,
    
    # ========================================================================
    # BRIDGE TABLE MAPPINGS
    # ========================================================================
    
    # Bridge Table: request_customers
    # Table: request_customers | Relationship: Many-to-Many (Requests ↔ Customers)
    # Description: Store request associations for a customer
    # Fields: request_id (FK -> requests.id), customer_id (FK -> customers.id), id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "request_customers": [
        {
            # Column: request_id | Type: Integer | Required | FK: requests.id
            # Description: Request ID - Foreign key to requests table
            "request_id": 100,
            
            # Note: customer_id is set automatically when creating request_customers for a customer
            # customer_id: customer.id
        },
        {
            "request_id": 101,
        },
    ],
}

