"""
Request Payload Format Documentation

This file defines the complete payload format for storing request/deal data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).
"""

from typing import Any, Dict, List, Optional


# ============================================================================
# REQUEST PAYLOAD FORMAT
# Single payload structure with all request fields and bridge table mappings
# ============================================================================

REQUEST_PAYLOAD: Dict[str, Any] = {
    # ========================================================================
    # PRIMARY KEY & IDENTIFIERS
    # ========================================================================
    
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented request ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: bitrix_id | Type: Integer | Required | Not Null
    # Description: Bitrix24 request ID - Unique identifier from Bitrix24 system
    "bitrix_id": 5001,
    
    # Column: deal_id | Type: String(36) | Required | Not Null | Unique
    # Description: Deal ID - Unique deal identifier (UUID format)
    "deal_id": "550e8400-e29b-41d4-a716-446655440000",
    
    # ========================================================================
    # BASIC REQUEST INFORMATION
    # ========================================================================
    
    # Column: name | Type: String(150) | Required | Not Null
    # Description: Request name - Request/deal name
    "name": "Q1 2025 Dairy Order",
    
    # Column: request_type | Type: String(50) | Nullable
    # Description: Request type - Type of request (e.g., 'order', 'inquiry', 'quote')
    "request_type": "order",
    
    # Column: deal_stage | Type: String(100) | Required | Not Null
    # Description: Deal stage - Current deal stage
    "deal_stage": "negotiation",
    
    # Column: probability | Type: Integer | Required | Not Null
    # Description: Probability - Deal probability percentage (0-100)
    "probability": 75,
    
    # Column: description | Type: Text | Required | Not Null
    # Description: Request description - Detailed request description (stored as string)
    "description": "Large order for dairy products including butter, cheese, and milk for Q1 2025.",
    
    # ========================================================================
    # FINANCIAL INFORMATION
    # ========================================================================
    
    # Column: currency | Type: String(3) | Required | Not Null
    # Description: Currency - ISO currency code (e.g., 'USD', 'EUR', 'BRL')
    "currency": "BRL",
    
    # Column: total | Type: Float | Required | Not Null
    # Description: Total - Total deal amount
    "total": 50000.00,
    
    # Column: tax_rate | Type: Float | Required | Not Null
    # Description: Tax rate - Tax rate percentage
    "tax_rate": 18.0,
    
    # Column: freight_charges | Type: Float | Required | Not Null
    # Description: Freight charges - Shipping/freight charges
    "freight_charges": 2500.00,
    
    # Column: advance_payment | Type: Float | Required | Not Null
    # Description: Advance payment - Advance payment amount
    "advance_payment": 10000.00,
    
    # ========================================================================
    # STATUS & FLAGS (Boolean fields)
    # ========================================================================
    
    # Column: is_manual_opportunity | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether is manual opportunity - Manual creation flag
    # Enum: True = Manually created opportunity, False = Auto-generated opportunity
    "is_manual_opportunity": False,
    
    # Column: available_to_everyone | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether available to everyone - Visibility flag
    # Enum: True = Request is available to everyone, False = Request is restricted
    "available_to_everyone": False,
    
    # Column: opened | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether opened - Open status flag
    # Enum: True = Request is opened, False = Request is not opened
    "opened": True,
    
    # Column: closed | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether closed - Closed status flag
    # Enum: True = Request is closed, False = Request is not closed
    "closed": False,
    
    # Column: new_deal | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether new deal - New deal flag
    # Enum: True = This is a new deal, False = This is not a new deal
    "new_deal": True,
    
    # Column: recurring_deal | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether recurring deal - Recurring deal flag
    # Enum: True = This is a recurring deal, False = This is not a recurring deal
    "recurring_deal": False,
    
    # Column: repeat_deal | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether repeat deal - Repeat deal flag
    # Enum: True = This is a repeat deal, False = This is not a repeat deal
    "repeat_deal": False,
    
    # Column: advised | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether advised - Advised status flag
    # Enum: True = Advised, False = Not advised
    "advised": False,
    
    # Column: lc | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether LC (Letter of Credit) - LC flag
    # Enum: True = Letter of Credit required, False = Letter of Credit not required
    "lc": False,
    
    # Column: origin_accepted | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether origin is accepted - Origin acceptance flag
    # Enum: True = Origin is accepted, False = Origin is not accepted
    "origin_accepted": True,
    
    # Column: po2factory_customer | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether PO to factory customer - PO to factory flag
    # Enum: True = PO to factory customer, False = Not PO to factory customer
    "po2factory_customer": False,
    
    # Column: eta_required_by_client | Type: Boolean | Required | Not Null | Default: False
    # Description: Whether ETA required by client - ETA requirement flag
    # Enum: True = ETA required by client, False = ETA not required by client
    "eta_required_by_client": True,
    
    # ========================================================================
    # ENUM FIELDS (stored as string values)
    # ========================================================================
    
    # Column: source | Type: EnumTypeDecorator(Source) | Required | Not Null | Default: Source.BITRIX
    # Description: Source - Request source system (stored as string: 'bitrix', 'manual', etc.)
    "source": "bitrix",
    
    # Column: request_status | Type: EnumTypeDecorator(RequestStatus) | Required | Not Null | Default: RequestStatus.NEW_UNCLEAR
    # Description: Request status - Request status (stored as string: 'new_unclear', 'active', 'completed', etc.)
    "request_status": "active",
    
    # Column: phase | Type: EnumTypeDecorator(RequestPhase) | Required | Not Null | Default: RequestPhase.LEAD
    # Description: Phase - Request phase (stored as string: 'lead', 'inquiry', 'order', etc.)
    "phase": "inquiry",
    
    # Column: current_stage_status | Type: EnumTypeDecorator(StageStatus) | Required | Not Null | Default: StageStatus.NEW_UNCLEAR
    # Description: Current stage status - Current stage status (stored as string: 'new_unclear', 'in_progress', 'completed', etc.)
    "current_stage_status": "in_progress",
    
    # Column: next_stage_status | Type: EnumTypeDecorator(StageStatus) | Nullable
    # Description: Next stage status - Next stage status (stored as string)
    "next_stage_status": "pending",
    
    # ========================================================================
    # DATES & TIMESTAMPS (DateTime stored as string in ISO format)
    # ========================================================================
    
    # Column: start_date | Type: DateTime | Required | Not Null
    # Description: Start date - Request start date (stored as string)
    "start_date": "2025-01-01T00:00:00+00:00",
    
    # Column: end_date | Type: DateTime | Required | Not Null
    # Description: End date - Request end date (stored as string)
    "end_date": "2025-03-31T23:59:59+00:00",
    
    # Column: inquiry_date | Type: DateTime | Required | Not Null
    # Description: Inquiry date - Date of inquiry (stored as string)
    "inquiry_date": "2024-12-15T10:00:00+00:00",
    
    # Column: production_date | Type: DateTime | Required | Not Null
    # Description: Production date - Production date (stored as string)
    "production_date": "2025-02-01T00:00:00+00:00",
    
    # Column: loading_date | Type: DateTime | Required | Not Null
    # Description: Loading date - Loading date (stored as string)
    "loading_date": "2025-02-15T00:00:00+00:00",
    
    # Column: etd | Type: DateTime | Required | Not Null
    # Description: ETD (Estimated Time of Departure) - ETD date (stored as string)
    "etd": "2025-02-20T00:00:00+00:00",
    
    # Column: eta | Type: DateTime | Required | Not Null
    # Description: ETA (Estimated Time of Arrival) - ETA date (stored as string)
    "eta": "2025-03-10T00:00:00+00:00",
    
    # Column: latest_date_of_shipment | Type: DateTime | Required | Not Null
    # Description: Latest date of shipment - Latest shipment date (stored as string)
    "latest_date_of_shipment": "2025-02-25T00:00:00+00:00",
    
    # Column: lc_expiry_date | Type: DateTime | Required | Not Null
    # Description: LC expiry date - Letter of Credit expiry date (stored as string)
    "lc_expiry_date": "2025-04-30T00:00:00+00:00",
    
    # Column: shipping_date | Type: DateTime | Required | Not Null
    # Description: Shipping date - Actual shipping date (stored as string)
    "shipping_date": "2025-02-22T00:00:00+00:00",
    
    # Column: cargo_readiness_date | Type: DateTime | Required | Not Null
    # Description: Cargo readiness date - Cargo readiness date (stored as string)
    "cargo_readiness_date": "2025-02-10T00:00:00+00:00",
    
    # Column: next_lots_loading_dates | Type: DateTime | Required | Not Null
    # Description: Next lots loading dates - Next lots loading date (stored as string)
    "next_lots_loading_dates": "2025-03-01T00:00:00+00:00",
    
    # Column: moved_time | Type: DateTime | Required | Not Null
    # Description: Moved time - Time when request was moved (stored as string)
    "moved_time": "2025-01-10T14:30:00+00:00",
    
    # Column: last_activity_time | Type: DateTime | Required | Not Null
    # Description: Last activity time - Last activity timestamp (stored as string)
    "last_activity_time": "2025-01-20T16:45:00+00:00",
    
    # Column: last_communication_time | Type: DateTime | Required | Not Null
    # Description: Last communication time - Last communication timestamp (stored as string)
    "last_communication_time": "2025-01-18T11:20:00+00:00",
    
    # ========================================================================
    # RELATIONSHIPS & FOREIGN KEYS
    # ========================================================================
    
    # Column: company_id | Type: Integer | Nullable | FK: suppliers.id
    # Description: Company ID - Foreign key to suppliers table
    "company_id": 10,
    
    # Column: contact_id | Type: Integer | Required | Not Null
    # Description: Contact ID - Contact identifier
    "contact_id": 100,
    
    # Column: estimate_id | Type: Integer | Required | Not Null
    # Description: Estimate ID - Estimate identifier
    "estimate_id": 200,
    
    # Column: current_stage_id | Type: Integer | Nullable | FK: stages.id
    # Description: Current active stage ID - Foreign key to stages table
    "current_stage_id": 5,
    
    # Column: next_stage_id | Type: Integer | Nullable | FK: stages.id
    # Description: Next stage ID in the workflow - Foreign key to stages table
    "next_stage_id": 6,
    
    # Column: responsible_person | Type: Integer | Nullable
    # Description: Bitrix user ID of responsible person - Responsible person Bitrix ID
    "responsible_person": 218,
    
    # Column: assigned_by | Type: Integer | Nullable | FK: users.id
    # Description: User ID mapped from responsible_person Bitrix ID - Foreign key to users table
    "assigned_by": 1,
    
    # Column: created_by | Type: Integer | Required | Not Null
    # Description: Created by - Bitrix user ID who created the request
    "created_by": 78,
    
    # Column: modified_by | Type: Integer | Required | Not Null
    # Description: Modified by - Bitrix user ID who last modified the request
    "modified_by": 218,
    
    # Column: moved_by_id | Type: Integer | Required | Not Null
    # Description: Moved by ID - User ID who moved the request
    "moved_by_id": 218,
    
    # Column: last_activity_by | Type: Integer | Required | Not Null
    # Description: Last activity by - User ID who performed last activity
    "last_activity_by": 218,
    
    # Column: repeat_sale_segment_id | Type: Integer | Required | Not Null
    # Description: Repeat sale segment ID - Repeat sale segment identifier
    "repeat_sale_segment_id": 1,
    
    # ========================================================================
    # ADDITIONAL INFORMATION (Text fields - stored as string)
    # ========================================================================
    
    # Column: comment | Type: Text | Required | Not Null
    # Description: Comment - General comments about request (stored as string)
    "comment": "High priority order. Client requires fast delivery.",
    
    # Column: additional_information | Type: Text | Required | Not Null
    # Description: Additional information - Additional request information (stored as string)
    "additional_information": "Special packaging requirements. Temperature controlled shipping required.",
    
    # Column: postscript | Type: Text | Required | Not Null
    # Description: Postscript - Postscript notes (stored as string)
    "postscript": "Please confirm availability before proceeding.",
    
    # ========================================================================
    # PIPELINE & STAGE INFORMATION
    # ========================================================================
    
    # Column: pipeline | Type: String(100) | Required | Not Null
    # Description: Pipeline - Pipeline identifier
    "pipeline": "sales_pipeline_1",
    
    # Column: stage_group | Type: String(100) | Required | Not Null
    # Description: Stage group - Stage group identifier
    "stage_group": "negotiation_group",
    
    # Column: repeat_inquiry | Type: String(100) | Required | Not Null
    # Description: Repeat inquiry - Repeat inquiry identifier
    "repeat_inquiry": "",
    
    # ========================================================================
    # SOURCE & EXTERNAL INFORMATION
    # ========================================================================
    
    # Column: source_information | Type: String(100) | Required | Not Null
    # Description: Source information - Source information
    "source_information": "website",
    
    # Column: external_source | Type: String(100) | Required | Not Null
    # Description: External source - External source identifier
    "external_source": "bitrix",
    
    # Column: lead_source | Type: String(100) | Nullable
    # Description: Lead source - Lead source identifier
    "lead_source": "website_form",
    
    # Column: item_id_in_data_source | Type: Integer | Required | Not Null
    # Description: Item ID in data source - External system item ID
    "item_id_in_data_source": 12345,
    
    # ========================================================================
    # MARKETING & CAMPAIGN INFORMATION
    # ========================================================================
    
    # Column: ad_system | Type: String(50) | Required | Not Null
    # Description: Ad system - Advertising system identifier
    "ad_system": "google",
    
    # Column: medium | Type: String(50) | Required | Not Null
    # Description: Medium - Marketing medium
    "medium": "cpc",
    
    # Column: ad_campaign_utm | Type: String(200) | Required | Not Null
    # Description: Ad campaign UTM - UTM campaign identifier
    "ad_campaign_utm": "summer_sale_2025",
    
    # Column: campaign_contents | Type: String(200) | Required | Not Null
    # Description: Campaign contents - Campaign content identifier
    "campaign_contents": "banner_ad_v1",
    
    # Column: campaign_search_term | Type: String(200) | Required | Not Null
    # Description: Campaign search term - Search term used in campaign
    "campaign_search_term": "dairy products",
    
    # ========================================================================
    # PURCHASE ORDER & REFERENCE INFORMATION
    # ========================================================================
    
    # Column: purchase_order | Type: String(50) | Required | Not Null
    # Description: Purchase order - Purchase order number
    "purchase_order": "PO-2025-001",
    
    # Column: ref_code | Type: String(36) | Required | Not Null
    # Description: Reference code - Reference code identifier
    "ref_code": "REF-2025-001",
    
    # Column: client_reference_number | Type: String(50) | Required | Not Null
    # Description: Client reference number - Client's reference number
    "client_reference_number": "CLIENT-REF-001",
    
    # Column: pi_number | Type: String(50) | Required | Not Null
    # Description: PI number - Proforma Invoice number
    "pi_number": "PI-2025-001",
    
    # ========================================================================
    # LOGISTICS & SHIPPING INFORMATION
    # ========================================================================
    
    # Column: forwarder | Type: String(150) | Required | Not Null
    # Description: Forwarder - Forwarding company name
    "forwarder": "ABC Logistics Ltd.",
    
    # Column: shipping_line | Type: String(150) | Required | Not Null
    # Description: Shipping line - Shipping line company name
    "shipping_line": "Maersk Line",
    
    # Column: incoterm | Type: String(10) | Required | Not Null
    # Description: Incoterm - Incoterms code (e.g., 'FOB', 'CIF', 'EXW')
    "incoterm": "FOB",
    
    # Column: port_of_loading | Type: String(100) | Required | Not Null
    # Description: Port of loading - Port of loading name
    "port_of_loading": "Santos, Brazil",
    
    # Column: port_of_discharge | Type: String(100) | Required | Not Null
    # Description: Port of discharge - Port of discharge name
    "port_of_discharge": "Los Angeles, USA",
    
    # Column: country_of_destination | Type: String(100) | Required | Not Null
    # Description: Country of destination - Destination country name
    "country_of_destination": "United States",
    
    # Column: country | Type: String(100) | Required | Not Null
    # Description: Country - Country name
    "country": "United States",
    
    # Column: container_number | Type: String(50) | Required | Not Null
    # Description: Container number - Shipping container number
    "container_number": "CONT-123456",
    
    # Column: loaded_container_quantity | Type: Integer | Required | Not Null
    # Description: Loaded container quantity - Number of containers loaded
    "loaded_container_quantity": 2,
    
    # Column: bl_no | Type: String(50) | Required | Not Null
    # Description: BL number - Bill of Lading number
    "bl_no": "BL-2025-001",
    
    # Column: shipment_tracking | Type: String(100) | Required | Not Null
    # Description: Shipment tracking - Shipment tracking number
    "shipment_tracking": "TRACK-123456789",
    
    # Column: doc_to_client_track_id | Type: String(50) | Required | Not Null
    # Description: Document to client track ID - Document tracking ID
    "doc_to_client_track_id": "DOC-TRACK-001",
    
    # ========================================================================
    # BANKING & FINANCIAL INFORMATION
    # ========================================================================
    
    # Column: issuing_bank | Type: String(150) | Required | Not Null
    # Description: Issuing bank - Issuing bank name
    "issuing_bank": "Bank of America",
    
    # Column: advising_bank | Type: String(150) | Required | Not Null
    # Description: Advising bank - Advising bank name
    "advising_bank": "Banco do Brasil",
    
    # Column: confirming_bank | Type: String(150) | Required | Not Null
    # Description: Confirming bank - Confirming bank name
    "confirming_bank": "Citibank",
    
    # Column: issuing_bank_ref_number | Type: String(50) | Required | Not Null
    # Description: Issuing bank reference number - Issuing bank reference
    "issuing_bank_ref_number": "IB-REF-001",
    
    # Column: advising_bank_ref_number | Type: String(50) | Required | Not Null
    # Description: Advising bank reference number - Advising bank reference
    "advising_bank_ref_number": "AB-REF-001",
    
    # ========================================================================
    # PAYMENT TERMS
    # ========================================================================
    
    # Column: client_payment_term | Type: String(50) | Required | Not Null
    # Description: Client payment term - Client payment terms
    "client_payment_term": "Net 30",
    
    # Column: manufacture_payment_term | Type: String(50) | Required | Not Null
    # Description: Manufacturer payment term - Manufacturer payment terms
    "manufacture_payment_term": "Net 45",
    
    # Column: manufacturer_payment_term | Type: String(50) | Required | Not Null
    # Description: Manufacturer payment term (alternative) - Manufacturer payment terms
    "manufacturer_payment_term": "Net 45",
    
    # Column: manufacturer_delivery_terms | Type: String(50) | Required | Not Null
    # Description: Manufacturer delivery terms - Manufacturer delivery terms
    "manufacturer_delivery_terms": "FOB",
    
    # ========================================================================
    # COMPANY & CLIENT INFORMATION
    # ========================================================================
    
    # Column: buying_company | Type: String(150) | Required | Not Null
    # Description: Buying company - Buying company name
    "buying_company": "ABC Trading Co.",
    
    # Column: export_company | Type: String(150) | Required | Not Null
    # Description: Export company - Export company name
    "export_company": "XYZ Export Ltd.",
    
    # Column: ops | Type: String(100) | Required | Not Null
    # Description: OPS - Operations identifier
    "ops": "OPS001",
    
    # Column: buyer_type | Type: String(50) | Required | Not Null
    # Description: Buyer type - Buyer type classification
    "buyer_type": "wholesale",
    
    # Column: client_size | Type: String(50) | Required | Not Null
    # Description: Client size - Client size classification
    "client_size": "large",
    
    # Column: urgency_level | Type: String(50) | Required | Not Null
    # Description: Urgency level - Urgency level classification
    "urgency_level": "high",
    
    # Column: lead_rank | Type: Integer | Required | Not Null
    # Description: Lead rank - Lead ranking value
    "lead_rank": 5,
    
    # ========================================================================
    # VOLUME & COMMITMENT INFORMATION
    # ========================================================================
    
    # Column: week_commitment | Type: Integer | Required | Not Null
    # Description: Week commitment - Weekly commitment volume
    "week_commitment": 100,
    
    # Column: estimated_volume | Type: Integer | Required | Not Null
    # Description: Estimated volume - Estimated order volume
    "estimated_volume": 10000,
    
    # Column: sample_status | Type: String(50) | Required | Not Null
    # Description: Sample status - Sample status
    "sample_status": "approved",
    
    # Column: lost_reason | Type: String(100) | Required | Not Null
    # Description: Lost reason - Reason for lost deal
    "lost_reason": "",
    
    # Column: lead | Type: String(100) | Required | Not Null
    # Description: Lead - Lead identifier
    "lead": "LEAD-001",
    
    # ========================================================================
    # CONTACT INFORMATION
    # ========================================================================
    
    # Column: email | Type: String(100) | Required | Not Null
    # Description: Email - Contact email address
    "email": "contact@abctrading.com",
    
    # Column: phone | Type: String(20) | Required | Not Null
    # Description: Phone - Contact phone number
    "phone": "+1-555-123-4567",
    
    # Column: location | Type: String(200) | Required | Not Null
    # Description: Location - Contact location
    "location": "New York, USA",
    
    # Column: website | Type: String(200) | Required | Not Null
    # Description: Website - Company website
    "website": "https://www.abctrading.com",
    
    # Column: bitrix_url | Type: String(500) | Required | Not Null
    # Description: Bitrix URL - Bitrix24 URL for this request
    "bitrix_url": "https://dana.bitrix24.eu/crm/deal/details/5001/",
    
    # ========================================================================
    # JSON FIELDS (stored as list/dict)
    # ========================================================================
    
    # Column: hashtag | Type: JSON | Required | Not Null | Default: list
    # Description: Hashtag - List of hashtags (stored as JSON array)
    "hashtag": ["#dairy", "#q1", "#priority"],
    
    # Column: manufacturer | Type: JSON | Required | Not Null | Default: list
    # Description: Manufacturer - List of manufacturers (stored as JSON array)
    "manufacturer": ["Manufacturer A", "Manufacturer B"],
    
    # Column: shipping_documents | Type: JSON | Required | Not Null | Default: list
    # Description: Shipping documents - List of shipping documents (stored as JSON array)
    "shipping_documents": ["BL", "Invoice", "Packing List"],
    
    # Column: key_instructions_to_ops | Type: JSON | Required | Not Null | Default: list
    # Description: Key instructions to OPS - List of key instructions (stored as JSON array)
    "key_instructions_to_ops": ["Handle with care", "Temperature controlled"],
    
    # Column: product_category | Type: JSON | Required | Not Null | Default: list
    # Description: Product category - List of product categories (stored as JSON array)
    "product_category": ["dairy", "butter", "cheese"],
    
    # Column: observer_bitrixids | Type: JSON | Nullable
    # Description: List of observer Bitrix user IDs as JSON array (stored as JSON array)
    "observer_bitrixids": [218, 78, 100],
    
    # Column: observer_ids | Type: JSON | Nullable
    # Description: List of observer user IDs (mapped from observer_bitrixids) as JSON array (stored as JSON array)
    "observer_ids": [1, 2, 3],
    
    # ========================================================================
    # BRIDGE TABLE MAPPINGS
    # ========================================================================
    
    # Bridge Table: request_products
    # Table: request_products | Relationship: Many-to-Many (Requests ↔ Products)
    # Description: Store product associations for a request
    # Fields: request_id (FK -> requests.id), product_id (FK -> products.id), id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "request_products": [
        {
            # Column: product_id | Type: Integer | Required | FK: products.id
            # Description: Product ID - Foreign key to products table
            "product_id": 1,
        },
        {
            "product_id": 2,
        },
    ],
    
    # Bridge Table: request_customers
    # Table: request_customers | Relationship: Many-to-Many (Requests ↔ Customers)
    # Description: Store customer associations for a request
    # Fields: request_id (FK -> requests.id), customer_id (FK -> customers.id), id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "request_customers": [
        {
            # Column: customer_id | Type: Integer | Required | FK: customers.id
            # Description: Customer ID - Foreign key to customers table
            "customer_id": 10,
        },
        {
            "customer_id": 11,
        },
    ],
    
    # Bridge Table: stages
    # Table: stages | Relationship: One-to-Many (Request → Stages)
    # Description: Store stage information for a request (via parent_id FK in stages table)
    # Fields: parent_id (FK -> requests.id in stages table), stage_id (stages.id)
    # Format: List of dictionaries with only IDs (stored as list)
    "stages": [
        {
            # Column: stage_id | Type: Integer | Required | FK: stages.id
            # Description: Stage ID - Foreign key to stages table
            "stage_id": 5,
        },
        {
            "stage_id": 6,
        },
    ],
    
    # Bridge Table: request_stage_activities
    # Table: request_stage_activities | Relationship: One-to-Many (Request → Activities)
    # Description: Store stage activities for a request
    # Fields: request_id (FK -> requests.id), stage_id (FK -> stages.id), activity_name, activity_type, and more...
    # Format: List of dictionaries with only IDs (stored as list)
    "request_stage_activities": [
        {
            # Column: activity_id | Type: Integer | Required | FK: request_stage_activities.id
            # Description: Activity ID - Foreign key to request_stage_activities table
            "activity_id": 1,
        },
        {
            "activity_id": 2,
        },
    ],
}

