"""
Product Payload Format Documentation

This file defines the complete payload format for storing product data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).
"""

from typing import Any, Dict, List, Optional


# ============================================================================
# PRODUCT PAYLOAD FORMAT
# Single payload structure with all product fields and bridge table mappings
# ============================================================================

PRODUCT_PAYLOAD: Dict[str, Any] = {
    # ========================================================================
    # PRIMARY KEY & IDENTIFIERS
    # ========================================================================
    
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented product ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: bitrix_id | Type: Integer | Required | Not Null
    # Description: Bitrix24 product ID - Unique identifier from Bitrix24 system
    "bitrix_id": 10772,
    
    # Column: xml_id | Type: String(255) | Nullable
    # Description: XML identifier - External system identifier for product
    "xml_id": "10772",
    
    # ========================================================================
    # BASIC PRODUCT INFORMATION
    # ========================================================================
    
    # Column: name | Type: String(255) | Nullable
    # Description: Product name - Full product name/title
    "name": "Dana Extra Unsalted Butter 82% Min. Fat, 16 % Max. Moisture 100g",
    
    # Column: product_short_name | Type: String(255) | Nullable
    # Description: Short product name - Abbreviated product name
    "product_short_name": "Dana Butter 100g",
    
    # Column: code | Type: String(255) | Nullable
    # Description: Product code - SKU or product code
    "code": "butter_100g",
    
    # Column: art_number | Type: String(255) | Nullable
    # Description: Article number - Manufacturer article number
    "art_number": "ART123456",
    
    # Column: description | Type: String(255) | Nullable
    # Description: Product description - Short product description
    "description": "Premium quality unsalted butter",
    
    # Column: description_type | Type: String(255) | Nullable
    # Description: Description format type - Format of description (e.g., 'html', 'text')
    "description_type": "html",
    
    # Column: specifications | Type: Text | Nullable
    # Description: Product specifications - Detailed technical specifications (stored as string)
    "specifications": "Fat content: 82% min, Moisture: 16% max",
    
    # ========================================================================
    # STATUS & FLAGS (Boolean fields)
    # ========================================================================
    
    # Column: active | Type: Boolean | Nullable | Default: True
    # Description: Whether product is active - Product availability status
    # Enum: True = Product is active and available, False = Product is inactive/hidden
    "active": True,
    
    # Column: bestseller | Type: Boolean | Nullable
    # Description: Bestseller flag - Indicates if product is a bestseller
    # Enum: True = Product is marked as bestseller, False = Product is not a bestseller
    "bestseller": False,
    
    # Column: special_offer | Type: Boolean | Nullable
    # Description: Special offer flag - Indicates if product is on special offer
    # Enum: True = Product is on special offer, False = Product is not on special offer
    "special_offer": False,
    
    # Column: has_supplier | Type: Boolean | Nullable | Default: False
    # Description: Whether product has a supplier - Supplier association flag
    # Enum: True = Product has associated supplier(s), False = Product has no supplier
    "has_supplier": True,
    
    # Column: vat_included | Type: Boolean | Nullable
    # Description: Whether VAT is included - Tax inclusion in price
    # Enum: True = VAT is included in price, False = VAT is not included in price
    "vat_included": True,
    
    # Column: art_works_approved_by_fda_of_country_of_destination | Type: Boolean | Nullable
    # Description: Art works approved by FDA - FDA approval status for artwork
    # Enum: True = Artworks approved by FDA, False = Artworks not approved by FDA
    "art_works_approved_by_fda_of_country_of_destination": False,
    
    # ========================================================================
    # PRICING & FINANCIAL
    # ========================================================================
    
    # Column: price | Type: Float | Nullable
    # Description: Price of product - Product price in base currency
    "price": 15.99,
    
    # Column: currency_id | Type: String(36) | Nullable
    # Description: Currency code - ISO currency code (e.g., 'USD', 'EUR', 'BRL')
    "currency_id": "BRL",
    
    # Column: vat_id | Type: Integer | Nullable
    # Description: VAT identifier - VAT tax rate ID
    "vat_id": 1,
    
    # ========================================================================
    # IMAGES & MEDIA (Text fields - stored as string)
    # ========================================================================
    
    # Column: preview_picture | Type: Text | Nullable
    # Description: Preview picture - URL or path to product preview image (stored as string)
    "preview_picture": "https://example.com/images/product-preview.jpg",
    
    # Column: detail_picture | Type: Text | Nullable
    # Description: Detail picture - URL or path to product detail image (stored as string)
    "detail_picture": "https://example.com/images/product-detail.jpg",
    
    # Column: background_image | Type: String(255) | Nullable
    # Description: Background image - URL or path to product background image
    "background_image": "https://example.com/images/product-bg.jpg",
    
    # Column: factory_logo | Type: Text | Nullable
    # Description: Factory logo - URL or path to factory/manufacturer logo (stored as string)
    "factory_logo": "https://example.com/logos/factory-logo.png",
    
    # Column: product_artwork | Type: Text | Nullable
    # Description: Product artwork - URL or path to product artwork files (stored as string)
    "product_artwork": "https://example.com/artwork/product-artwork.pdf",
    
    # Column: carton_artwork | Type: Text | Nullable
    # Description: Carton artwork - URL or path to carton artwork files (stored as string)
    "carton_artwork": "https://example.com/artwork/carton-artwork.pdf",
    
    # Column: primary_packing_artwork | Type: Text | Nullable
    # Description: Primary packing artwork - URL or path to primary packing artwork (stored as string)
    "primary_packing_artwork": "https://example.com/artwork/primary-packing.pdf",
    
    # Column: secondary_packing_artwork | Type: Text | Nullable
    # Description: Secondary packing artwork - URL or path to secondary packing artwork (stored as string)
    "secondary_packing_artwork": "https://example.com/artwork/secondary-packing.pdf",
    
    # Column: photo_of_primary_packing | Type: Text | Nullable
    # Description: Photo of primary packing - URL or path to primary packing photo (stored as string)
    "photo_of_primary_packing": "https://example.com/photos/primary-packing.jpg",
    
    # Column: photo_of_secondary_packing | Type: Text | Nullable
    # Description: Photo of secondary packing - URL or path to secondary packing photo (stored as string)
    "photo_of_secondary_packing": "https://example.com/photos/secondary-packing.jpg",
    
    # Column: product_keylines | Type: Text | Nullable
    # Description: Product keylines - URL or path to product keylines file (stored as string)
    "product_keylines": "https://example.com/keylines/product-keylines.pdf",
    
    # Column: link_to_artwork_files | Type: Text | Nullable
    # Description: Link to artwork files - URL or path to artwork files collection (stored as string)
    "link_to_artwork_files": "https://example.com/artwork/",
    
    # Column: technical_data_sheet | Type: Text | Nullable
    # Description: Technical data sheet - URL or path to technical data sheet (stored as string)
    "technical_data_sheet": "https://example.com/docs/technical-sheet.pdf",
    
    # ========================================================================
    # BARCODES & IDENTIFICATION
    # ========================================================================
    
    # Column: barcode | Type: String(255) | Nullable
    # Description: Product barcode - EAN/UPC barcode for product
    "barcode": "7891234567890",
    
    # Column: carton_barcode | Type: String(255) | Nullable
    # Description: Carton barcode - Barcode for carton/packaging
    "carton_barcode": "7891234567891",
    
    # ========================================================================
    # CATEGORIZATION
    # ========================================================================
    
    # Column: category_id | Type: Integer | Nullable | FK: categories.id
    # Description: Category ID - Foreign key to categories table (main category)
    "category_id": 5,
    
    # Column: parent_category_id | Type: Integer | Nullable | FK: categories.id
    # Description: Parent Category ID - Foreign key to categories table (parent category)
    "parent_category_id": 3,
    
    # Column: sub_category_id | Type: Integer | Nullable | FK: categories.id
    # Description: Sub Category ID - Foreign key to categories table (sub category)
    "sub_category_id": 7,
    
    # Column: product_category | Type: String(255) | Nullable
    # Description: Product category code - Category code/name as string
    "product_category": "DAIRY",
    
    # Column: catalog_id | Type: Integer | Nullable
    # Description: Catalog identifier - Bitrix catalog ID
    "catalog_id": 24,
    
    # Column: section_id | Type: Integer | Nullable
    # Description: Section identifier - Bitrix section ID
    "section_id": 334,
    
    # ========================================================================
    # SUPPLIER INFORMATION
    # ========================================================================
    
    # Column: supplier_id | Type: Integer | Nullable | FK: suppliers.id
    # Description: Supplier unique identifier - Foreign key to suppliers table (primary supplier)
    "supplier_id": 10,
    
    # Column: supplier_name | Type: String(255) | Nullable
    # Description: Supplier company name - Name of the supplier company
    "supplier_name": "Dana Dairy Products Ltd.",
    
    # Column: factory | Type: String(255) | Nullable
    # Description: Factory/Supplier ID - Factory identifier or supplier code
    "factory": "FACTORY_001",
    
    # ========================================================================
    # PACKAGING & DIMENSIONS
    # ========================================================================
    
    # Column: unit_pack_size | Type: Integer | Nullable
    # Description: Unit pack size - Number of units per pack
    "unit_pack_size": 12,
    
    # Column: units_per_carton | Type: Integer | Nullable
    # Description: Units per carton - Number of units in a carton (e.g., 12 x 1L)
    "units_per_carton": 12,
    
    # Column: cartons_per_pallet | Type: Integer | Nullable
    # Description: Number of cartons per pallet - Cartons that fit on one pallet
    "cartons_per_pallet": 50,
    
    # Column: sku_package | Type: String(255) | Nullable
    # Description: SKU package units - Package description (e.g., '10 slices', '4 cups')
    "sku_package": "10 slices",
    
    # Column: packing | Type: String(255) | Nullable
    # Description: Packing type - Type of packing used
    "packing": "Box",
    
    # Column: carton | Type: String(255) | Nullable
    # Description: Carton specification - Carton type/specification
    "carton": "Standard Carton",
    
    # Column: carton_dimensions | Type: String(255) | Nullable
    # Description: Carton dimensions - Dimensions of carton (e.g., '40x30x20 cm')
    "carton_dimensions": "40x30x20 cm",
    
    # Column: pallet_dimensions | Type: String(255) | Nullable
    # Description: Pallet dimensions - Dimensions of pallet
    "pallet_dimensions": "120x80x144 cm",
    
    # ========================================================================
    # CONTENT & WEIGHT
    # ========================================================================
    
    # Column: net_content | Type: Float | Nullable
    # Description: Net content/weight - Net weight or content amount
    "net_content": 100.0,
    
    # ========================================================================
    # ORIGIN & COMPLIANCE
    # ========================================================================
    
    # Column: country_of_origin | Type: String(255) | Nullable
    # Description: Country of origin code - ISO country code of origin
    "country_of_origin": "BR",
    
    # Column: origin | Type: String(255) | Nullable
    # Description: Origin - Product origin information
    "origin": "Brazil",
    
    # Column: hs_code | Type: String(255) | Nullable
    # Description: Harmonized System tariff code - HS code for customs/tariff classification
    "hs_code": "04051019",
    
    # Column: package_material | Type: String(255) | Nullable
    # Description: Packaging material code - Code for packaging material type
    "package_material": "PLASTIC",
    
    # Column: documents_from_factory | Type: Text | Nullable
    # Description: Documents from factory - Factory documents (COO, HC, FSC certificates) (stored as string)
    "documents_from_factory": "COO: Yes, HC: Yes, FSC: No",
    
    # ========================================================================
    # STORAGE & SHELF LIFE
    # ========================================================================
    
    # Column: shelf_life | Type: Integer | Nullable
    # Description: Product shelf life - Shelf life in days
    "shelf_life": 120,
    
    # Column: storage_conditions_temperature | Type: String(255) | Nullable
    # Description: Storage conditions temperature - Storage temperature requirements
    "storage_conditions_temperature": "Store at temperatures up to 10ºC",
    
    # Column: transport_conditions_temperature | Type: String(255) | Nullable
    # Description: Transport conditions temperature - Transport temperature requirements
    "transport_conditions_temperature": "Transport at 2-8°C",
    
    # ========================================================================
    # LOGISTICS & DELIVERY
    # ========================================================================
    
    # Column: loading_quantities | Type: String(255) | Nullable
    # Description: Loading quantities - Available loading quantities (e.g., '20' FCL – 40' FCL – FTL') (stored as string)
    "loading_quantities": "20' FCL – 40' FCL – FTL",
    
    # Column: loading_address | Type: String(255) | Nullable
    # Description: Loading address - Address where product is loaded/shipped from
    "loading_address": "Colônia das Missões, Gleba nº 3-FB Área Rural de Francisco Beltrão PR BRASIL",
    
    # Column: term_of_delivery | Type: Integer | Nullable
    # Description: Delivery terms (Incoterms) - Incoterms code for delivery terms
    "term_of_delivery": 1,
    
    # ========================================================================
    # LEAD TIMES
    # ========================================================================
    
    # Column: lead_time_to_print_packing_material | Type: Integer | Nullable
    # Description: Lead time to print packing material - Days required to print packing material
    "lead_time_to_print_packing_material": 7,
    
    # Column: lead_time_to_reorder_packing_material | Type: Integer | Nullable
    # Description: Lead time to reorder packing material - Days required to reorder packing material
    "lead_time_to_reorder_packing_material": 14,
    
    # Column: lead_time_to_production | Type: Integer | Nullable
    # Description: Lead time to production - Days required for production
    "lead_time_to_production": 21,
    
    # ========================================================================
    # MINIMUM ORDER QUANTITIES (MOQ)
    # ========================================================================
    
    # Column: moq_packaging_matereal | Type: Integer | Nullable
    # Description: Minimum order quantity for packaging material - MOQ for packaging
    "moq_packaging_matereal": 1000,
    
    # Column: moq_production | Type: Integer | Nullable
    # Description: Minimum order quantity for production - MOQ for production
    "moq_production": 5000,
    
    # ========================================================================
    # MEASUREMENT & UNITS
    # ========================================================================
    
    # Column: measure | Type: Integer | Nullable
    # Description: Unit of measure - Measure unit ID
    "measure": 1,
    
    # Column: sort | Type: Integer | Nullable | Default: 0
    # Description: Sort order - Display/sort order for product listing
    "sort": 500,
    
    # Column: quantity | Type: Integer | Nullable
    # Description: Quantity - Available quantity
    "quantity": 1000,
    
    # ========================================================================
    # METADATA & AUDIT FIELDS (DateTime stored as string in ISO format)
    # ========================================================================
    
    # Column: timestamp_x | Type: DateTime | Nullable
    # Description: Last modification timestamp - Last update time from Bitrix24 (stored as string)
    "timestamp_x": "2025-12-29T12:33:17+03:00",
    
    # Column: date_create | Type: DateTime | Nullable
    # Description: Creation date - Product creation date from Bitrix24 (stored as string)
    "date_create": "2025-11-06T09:06:26+03:00",
    
    # Column: modified_by | Type: String(255) | Nullable
    # Description: User who last modified - Bitrix user ID who last modified the product
    "modified_by": "218",
    
    # Column: created_by | Type: String(255) | Nullable
    # Description: User who created - Bitrix user ID who created the product
    "created_by": "78",
    
    # Column: product | Type: String(255) | Nullable
    # Description: Product name variant - Alternative product name
    "product": "Butter",
    
    # ========================================================================
    # BRIDGE TABLE MAPPINGS
    # ========================================================================
    
    # Bridge Table: product_suppliers
    # Table: product_suppliers | Relationship: Many-to-Many (Products ↔ Suppliers)
    # Description: Store multiple supplier associations for a product
    # Fields: product_id (FK -> products.id), supplier_id (FK -> suppliers.id), name, id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "product_suppliers": [
        {
            # Column: supplier_id | Type: Integer | Required | FK: suppliers.id
            # Description: Supplier ID - Foreign key to suppliers table
            "supplier_id": 10,
            
            # Column: name | Type: String(255) | Nullable
            # Description: Name - Mapping name or description
            "name": "Primary Supplier",
        },
        {
            "supplier_id": 15,
            "name": "Secondary Supplier",
        },
    ],
    
    # Bridge Table: logistic
    # Table: logistic | Relationship: One-to-One (Product → Logistic)
    # Description: Store detailed logistic information for a product
    # Fields: product_id (FK -> products.id), cartons_per_pallet, loading_quantities (JSON), transport_delivery_conditions_temperature, storage_conditions_temperature, carton_dimensions, pallet_dimensions, term_of_delivery, id, created_at, updated_at, deleted_at
    # Format: Dictionary (stored as dict)
    "logistic": {
        # Column: cartons_per_pallet | Type: Integer | Required
        # Description: Number of cartons per pallet
        "cartons_per_pallet": 50,
        
        # Column: loading_quantities | Type: JSON | Required
        # Description: Loading quantities - JSON array of loading quantity options (stored as list/dict in database)
        "loading_quantities": ["20' FCL", "40' FCL", "FTL"],
        
        # Column: transport_delivery_conditions_temperature | Type: String(100) | Required
        # Description: Transport/delivery conditions temperature
        "transport_delivery_conditions_temperature": "2-8°C",
        
        # Column: storage_conditions_temperature | Type: String(100) | Required
        # Description: Storage conditions temperature
        "storage_conditions_temperature": "Up to 10°C",
        
        # Column: carton_dimensions | Type: String(100) | Required
        # Description: Carton dimensions
        "carton_dimensions": "40x30x20 cm",
        
        # Column: pallet_dimensions | Type: String(100) | Required
        # Description: Pallet dimensions
        "pallet_dimensions": "120x80x144 cm",
        
        # Column: term_of_delivery | Type: String(100) | Required
        # Description: Term of delivery (Incoterms)
        "term_of_delivery": "FOB",
    },
    
    # Bridge Table: request_products
    # Table: request_products | Relationship: Many-to-Many (Requests ↔ Products)
    # Description: Store product associations with requests/orders
    # Fields: request_id (FK -> requests.id), product_id (FK -> products.id), id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "request_products": [
        {
            # Column: request_id | Type: Integer | Required | FK: requests.id
            # Description: Request ID - Foreign key to requests table
            "request_id": 100,
        },
        {
            "request_id": 101,
        },
    ],
}


