import { Product, ProductFormData } from "@/types/product";

export function getProductFormInitialValues(product: Product): ProductFormData {
  const {
    preview_text,
    short_name,
    description,
    category,
    sub_category,
    child_category,
    net_content,
    sku_package,
    package_material,
    specification,
    shelf_life,
    sku_id,
    barcode,
    carton_barcode,
    hs_code,
    art_number,
    unit_pack_size,
    units_per_carton,
    brand_name,
    factory_name,
    country_of_origin,
    origin,
    loading_address,
    logistics_details,
    is_fda_approved,
  } = product || {};
  return {
    preview_text: preview_text || "",
    short_name: short_name || "",
    description: description || "",
    category: category || "",
    sub_category: sub_category || "",
    child_category: child_category || "",
    net_content: net_content || "",
    sku_package: sku_package || "",
    package_material: package_material || "",
    specification: specification || "",
    shelf_life: shelf_life || "",
    sku_id: sku_id || "",
    barcode: barcode || "",
    carton_barcode: carton_barcode || "",
    hs_code: hs_code || "",
    art_number: art_number || "",
    unit_pack_size: unit_pack_size || "",
    units_per_carton: units_per_carton || "",
    brand_name: brand_name || "",
    factory_name: factory_name || "",
    country_of_origin: country_of_origin || "",
    origin: origin || "",
    loading_address: loading_address || "",
    cartons_per_pallet: logistics_details?.cartons_per_pallet || "",
    loading_quantities: logistics_details?.loading_quantities || "",
    transport_temperature: logistics_details?.transport_temperature || "",
    storage_temperature: logistics_details?.storage_temperature || "",
    carton_dimensions: logistics_details?.carton_dimensions || "",
    pallet_dimensions: logistics_details?.pallet_dimensions || "",
    term_of_delivery: logistics_details?.term_of_delivery || "",
    is_fda_approved: is_fda_approved || false,
  };
}
