"""
Email Collection Payload Format Documentation

This file defines the complete payload format for storing email collection data in the database.
All field information (column_name, datatype, description) is in comments above each field.
The payload format matches exactly how data is stored in the database (Text=string, String=string, Integer=int, Boolean=bool, Float=float, DateTime=string, JSON=list/dict).
"""

from typing import Any, Dict, List, Optional
from datetime import datetime

# ============================================================================
# EMAIL AUTH PAYLOAD FORMAT
# ============================================================================

EMAIL_AUTH_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented email auth ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: provider | Type: String(255) | Required | Not Null
    # Description: Email provider - Provider type (outlook, gmail, exchange)
    "provider": "outlook",
    
    # Column: tenant_id | Type: String(255) | Required | Not Null
    # Description: Azure tenant ID - Microsoft Azure tenant identifier
    "tenant_id": "12345678-1234-1234-1234-123456789012",
    
    # Column: email | Type: String(255) | Required | Not Null
    # Description: Email address - Email address for the connector
    "email": "user@example.com",
    
    # Column: client_id | Type: String(255) | Required | Not Null
    # Description: Azure client ID - Microsoft Azure application client ID
    "client_id": "87654321-4321-4321-4321-210987654321",
    
    # Column: client_secret | Type: String(255) | Required | Not Null
    # Description: Azure client secret - Microsoft Azure application client secret
    "client_secret": "secret_key_here",
    
    # Column: is_active | Type: Boolean | Required | Not Null | Default: True
    # Description: Whether connector is active - Active status of the connector
    "is_active": True,
}

# ============================================================================
# EMAIL MAILBOX PAYLOAD FORMAT
# ============================================================================

EMAIL_MAILBOX_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented mailbox ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: email_auth_id | Type: Integer | Nullable | FK: email_auth.id
    # Description: Email auth account ID - Foreign key to email_auth table
    "email_auth_id": 1,
    
    # Column: app_id | Type: Integer | Nullable
    # Description: Application ID - Application ID associated with this mailbox
    "app_id": 1,
    
    # Column: email | Type: String(255) | Required | Not Null
    # Description: Email address to sync - Email address for synchronization
    "email": "mailbox@example.com",
    
    # Column: is_active | Type: Boolean | Required | Not Null | Default: True
    # Description: Whether mailbox is active - Active status for syncing
    "is_active": True,
    
    # Column: last_synced_at | Type: DateTime | Nullable
    # Description: Last sync timestamp - Timestamp of last successful sync
    "last_synced_at": "2025-12-30T10:00:00+00:00",
}

# ============================================================================
# EMAIL SYNC STATE PAYLOAD FORMAT
# ============================================================================

EMAIL_SYNC_STATE_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented sync state ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: email_mailbox_id | Type: Integer | Nullable | FK: email_mailboxes.id
    # Description: Email mailbox ID - Foreign key to email_mailboxes table
    "email_mailbox_id": 1,
    
    # Column: mailbox_folder | Type: String(255) | Nullable
    # Description: Mailbox folder - Folder name (e.g., 'Inbox', 'SentItems')
    "mailbox_folder": "Inbox",
    
    # Column: delta_link | Type: Text | Nullable
    # Description: Microsoft Graph delta link - Delta link URL for incremental sync (can be 500+ characters)
    "delta_link": "https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages/delta?$deltatoken=...",
    
    # Column: subscription_id | Type: String(255) | Nullable
    # Description: Microsoft Graph subscription ID - Subscription ID in GUID format
    "subscription_id": "12345678-1234-1234-1234-123456789012",
    
    # Column: subscription_expiration | Type: DateTime | Nullable
    # Description: Subscription expiration - Timestamp when subscription expires
    "subscription_expiration": "2025-12-31T23:59:59+00:00",
    
    # Column: sync_status | Type: String(255) | Nullable
    # Description: Synchronization status - Status of sync (INITIAL_SYNC_PENDING, INITIAL_SYNC_IN_PROGRESS, INITIAL_SYNC_COMPLETED, SYNC_ACTIVE, SYNC_PAUSED, SYNC_ERROR)
    "sync_status": "SYNC_ACTIVE",
    
    # Column: last_synced_at | Type: DateTime | Nullable
    # Description: Last sync timestamp - Timestamp of last successful sync
    "last_synced_at": "2025-12-30T10:00:00+00:00",
}

# ============================================================================
# CONVERSATION PAYLOAD FORMAT
# ============================================================================

CONVERSATION_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented conversation ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: microsoft_conversation_id | Type: String(500) | Nullable | Unique
    # Description: Microsoft conversation ID - Microsoft Message Thread ID (can be 200+ chars)
    "microsoft_conversation_id": "AAMkAGI2THk0...",
    
    # Column: subject | Type: Text | Nullable
    # Description: Conversation subject - Subject of the conversation
    "subject": "Project Discussion",
    
    # Column: participants_json | Type: JSON | Nullable
    # Description: Participants as JSON - All participants in the conversation as JSON array
    # Format: [{"email": "user@example.com", "name": "User Name"}]
    "participants_json": [
        {"email": "user1@example.com", "name": "User One"},
        {"email": "user2@example.com", "name": "User Two"}
    ],
    
    # Column: total_emails | Type: Integer | Nullable | Default: 0
    # Description: Total number of emails - Total messages in conversation
    "total_emails": 5,
    
    # Column: conversation_started_at | Type: DateTime | Nullable
    # Description: Conversation start timestamp - Timestamp of first message
    "conversation_started_at": "2025-12-01T09:00:00+00:00",
    
    # Column: conversation_ended_at | Type: DateTime | Nullable
    # Description: Conversation end timestamp - Timestamp of last message
    "conversation_ended_at": "2025-12-30T15:30:00+00:00",
}

# ============================================================================
# EMAIL PAYLOAD FORMAT
# ============================================================================

EMAIL_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented email ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: microsoft_message_id | Type: String(500) | Nullable | Unique
    # Description: Microsoft message ID - Microsoft messageId from Outlook (can be 200+ chars)
    "microsoft_message_id": "AAMkAGI2THk0...",
    
    # Column: conversation_id | Type: String(500) | Nullable
    # Description: Conversation identifier - Email conversation identifier (matches Conversations.microsoft_conversation_id)
    "conversation_id": "AAMkAGI2THk0...",
    
    # Column: sender_email | Type: String(255) | Nullable
    # Description: Sender email address - Email address of the sender
    "sender_email": "sender@example.com",
    
    # Column: sender_name | Type: String(500) | Nullable
    # Description: Sender name - Name of the sender (can include special chars)
    "sender_name": "John Doe",
    
    # Column: receiver_string | Type: Text | Nullable
    # Description: Receiver addresses as text - Email receiver address(es) as text
    "receiver_string": "receiver1@example.com, receiver2@example.com",
    
    # Column: receiver_json | Type: JSON | Nullable
    # Description: Receiver addresses as JSON - Email receiver address(es) as JSON array
    # Format: [{"email": "receiver1@example.com", "name": "Receiver One"}]
    "receiver_json": [
        {"email": "receiver1@example.com", "name": "Receiver One"},
        {"email": "receiver2@example.com", "name": "Receiver Two"}
    ],
    
    # Column: subject | Type: Text | Nullable
    # Description: Email subject - Subject line of the email
    "subject": "Meeting Request",
    
    # Column: content_text | Type: LONGTEXT | Nullable
    # Description: Email body content - Email body content (plain text) - can be very long
    "content_text": "This is the email body content...",
    
    # Column: sent_at | Type: DateTime | Nullable
    # Description: Sent timestamp - Email sent timestamp
    "sent_at": "2025-12-30T10:00:00+00:00",
    
    # Column: received_at | Type: DateTime | Nullable
    # Description: Received timestamp - Email received timestamp
    "received_at": "2025-12-30T10:05:00+00:00",
    
    # Column: has_attachment | Type: Boolean | Nullable | Default: False
    # Description: Whether email has attachments - Indicates if email has attachments
    "has_attachment": True,
    
    # Column: message_order | Type: Integer | Nullable
    # Description: Message order - Order of message in conversation (calculated)
    "message_order": 1,
    
    # Column: is_reply | Type: Boolean | Nullable | Default: False
    # Description: Whether email is a reply - Indicates if this email is a reply
    "is_reply": False,
    
    # Column: reply_to_message_id | Type: Integer | Nullable | FK: emails.id
    # Description: Reply to message ID - ID of email this is replying to
    "reply_to_message_id": None,
    
    # Column: mapping_id | Type: String(100) | Nullable
    # Description: Mapping ID - ID mapping to external entities (deal_id, lead_id, etc.)
    "mapping_id": "deal_12345",
    
    # Column: source_type | Type: Enum (EmailSourceType) | Nullable
    # Description: Source type - Source type of the email mapping
    # Enum values: 'outlook', 'bitrix24', 'onedrive'
    "source_type": "outlook",
    
    # Column: mapping_table | Type: Enum (EmailMappingTable) | Nullable
    # Description: Mapping table - Target mapping table
    # Enum values: 'request', 'supplier'
    "mapping_table": "request",
    
    # ========================================================================
    # BRIDGE TABLE MAPPINGS
    # ========================================================================
    
    # Bridge Table: email_attachments
    # Table: email_attachments | Relationship: One-to-Many (Email → EmailAttachments)
    # Description: Store attachments associated with this email
    # Fields: email_id (FK -> emails.id), attachment_id, filename, content_type, size, storage_path, is_inline, last_modified, id, created_at, updated_at, deleted_at
    # Format: List of dictionaries (stored as list)
    "email_attachments": [
        {
            # Column: attachment_id | Type: String(500) | Nullable
            # Description: Attachment ID from Outlook - Attachment ID (can be long)
            "attachment_id": "AAMkAGI2THk0...",
            
            # Column: filename | Type: String(500) | Nullable
            # Description: Attachment filename - Name of the attachment file
            "filename": "document.pdf",
            
            # Column: content_type | Type: String(255) | Nullable
            # Description: Content type - MIME type of the attachment
            "content_type": "application/pdf",
            
            # Column: size | Type: BigInteger | Nullable
            # Description: Attachment size - Size in bytes (supports files > 2GB)
            "size": 1024000,
            
            # Column: storage_path | Type: Text | Nullable
            # Description: Storage path - S3 URL or file path (can be very long)
            "storage_path": "https://s3.amazonaws.com/bucket/attachments/document.pdf",
            
            # Column: is_inline | Type: Boolean | Nullable | Default: False
            # Description: Whether attachment is inline - Indicates if attachment is inline
            "is_inline": False,
            
            # Column: last_modified | Type: DateTime | Nullable
            # Description: Last modified timestamp - Last modified time of attachment
            "last_modified": "2025-12-30T10:00:00+00:00",
            
            # Note: email_id is set automatically when creating attachments for an email
            # email_id: email.id
        },
    ],
}

# ============================================================================
# EMAIL ATTACHMENT PAYLOAD FORMAT
# ============================================================================

EMAIL_ATTACHMENT_PAYLOAD: Dict[str, Any] = {
    # Column: id | Type: Integer | Primary Key | Auto-increment
    # Description: Primary key - Auto-incremented attachment ID
    # Note: Do not include in create payload, auto-generated by database
    # "id": 1,  # Excluded from create payload
    
    # Column: email_id | Type: Integer | Required | Not Null | FK: emails.id
    # Description: Email ID - Foreign key to emails table
    "email_id": 1,
    
    # Column: attachment_id | Type: String(500) | Nullable
    # Description: Attachment ID from Outlook - Attachment ID (can be long)
    "attachment_id": "AAMkAGI2THk0...",
    
    # Column: filename | Type: String(500) | Nullable
    # Description: Attachment filename - Name of the attachment file
    "filename": "document.pdf",
    
    # Column: content_type | Type: String(255) | Nullable
    # Description: Content type - MIME type of the attachment
    "content_type": "application/pdf",
    
    # Column: size | Type: BigInteger | Nullable
    # Description: Attachment size - Size in bytes (supports files > 2GB)
    "size": 1024000,
    
    # Column: storage_path | Type: Text | Nullable
    # Description: Storage path - S3 URL or file path (can be very long)
    "storage_path": "https://s3.amazonaws.com/bucket/attachments/document.pdf",
    
    # Column: is_inline | Type: Boolean | Nullable | Default: False
    # Description: Whether attachment is inline - Indicates if attachment is inline
    "is_inline": False,
    
    # Column: last_modified | Type: DateTime | Nullable
    # Description: Last modified timestamp - Last modified time of attachment
    "last_modified": "2025-12-30T10:00:00+00:00",
}

